### ISSUE TITLE
Not working for me; I suspect I have my skill set up incorrectly

### ISSUE THREAD

**Issue by saanvik** [castanhocorreia/Library-Use-FoundryVTT#6]
I created a journal entry, marked all the text as Italian, then shared it with a character who has Italian at 30.  She could not read the journal entry.

On her character sheet, a 1920 character sheet, she has Italian as a specialization, Italian/Language.  

Foundry version 0.8.8
Game system version 0.6.2
Linux
Chromium browser

The version that's in English is what I created; see the choice of Italian.  The version in pseudo-italian is what she sees.  The final screenshot is her skill.   

![Screenshot_2021-08-15_20-29-19](https://user-images.githubusercontent.com/1077646/129507837-d79a419f-df8c-48a5-b25e-037ff5ec824c.png)
![Screenshot_2021-08-15_20-30-53](https://user-images.githubusercontent.com/1077646/129507927-d12c9456-6c18-40c5-86d8-9750ab95dedc.png)

![Screenshot_2021-08-15_20-28-04](https://user-images.githubusercontent.com/1077646/129507757-ee4d8892-6200-4db2-b96f-67631c746124.png)

**Comment by joaovscorreia** [comment]
Hello, @saanvik. One question: does you or your player use Foundry in a language other than English?

**Comment by saanvik** [comment]
Hey, thanks for reaching out.  No, both I and the user are in the US, using English.

**Comment by saanvik** [comment]
[actor-json.zip](https://github.com/castanhocorreia/Library-Use-FoundryVTT/files/7010858/actor-json.zip)

This is an export of the actor as requested in Discord.

**Comment by joaovscorreia** [comment]
Ah, now I get it. The character has an Italian value of 30. In the settings, the default value for understanding languages was 50. I believe you didn't change that.
![image](https://user-images.githubusercontent.com/80350000/130000000-d7f23dcb-3c07-4716-ac0a-b7a8180ec390.png)
Anyway, I released an update to change this default value to 1. I believe this will avoid misunderstandings.
Thank you very much for your report! If you have any other problems, please don't hesitate to say!
